#!/usr/bin/env python3
"""Emit Meson flag lists to ``flags.meson``.

This helper exists for Meson releases prior to 1.2 where
``configure_file()`` cannot easily handle list substitution.

Usage: ``gen_flags.py OUTPUT CFLAGS LDFLAGS``
where both flag lists are semicolon-separated strings.
"""
from __future__ import annotations

import sys
from pathlib import Path


def main(argv: list[str]) -> int:
    if len(argv) != 4:
        raise SystemExit('usage: gen_flags.py OUT "c1;c2" "ld1;ld2"')
    out_path = Path(argv[1])
    cflags = [f for f in argv[2].split(';') if f]
    ldflags = [f for f in argv[3].split(';') if f]

    with out_path.open('w', encoding='utf-8') as fh:
        fh.write('# Auto-generated by Meson\n')
        fh.write('common_cflags = [\n')
        for f in cflags:
            fh.write(f"  '{f}',\n")
        fh.write(']\n\n')
        fh.write('common_ldflags = [\n')
        for f in ldflags:
            fh.write(f"  '{f}',\n")
        fh.write(']\n')
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv))
