# Continuous integration workflow for Avrix
# Installs the *modern* AVR toolchain via `setup.sh --modern`,
# builds the firmware using Meson, and exports Sphinx/Doxygen docs
# as artifacts.

name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository sources
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install AVR GCC toolchain and required build utilities
      - name: Install AVR toolchain
        run: sudo ./setup.sh --modern

      # Install Meson build system from apt and verify the install
      - name: Install Meson
        run: |
          sudo apt-get update
          sudo apt-get install -y meson ninja-build
          meson --version

      # Configure the Meson build directory for the AVR target
      - name: Configure build
        run: meson setup build --cross-file cross/avr_m328p.txt

      # Compile all targets using ninja via Meson
      - name: Compile
        run: meson compile -C build

      # Execute any unit tests defined in the project
      - name: Run tests
        run: meson test -C build --print-errorlogs

      # Generate Doxygen and Sphinx documentation
      - name: Build documentation
        run: meson compile -C build doc-doxygen doc-sphinx

      # Archive the built documentation for inspection
      - name: Upload docs
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: build/docs
          if-no-files-found: warn
